baseURL: https://nxvhm.github.io/devnotes/
languageCode: en-us
title: Devnotes
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true

minify:
    disableXML: true
    minifyOutput: true


params:
  title: DevNotes
  description: "Devnotes"
  keywords: [Blog]
  author: Me
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

menu:
    main:
        - identifier: php
          name: php
          url: /php/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20
        - identifier: Devnotes
          name: nxvhm.github.io
          url: https://nxvhm.github.io/devnotes/
          weight: 30  